# -*- coding: utf-8 -*-
"""Homework5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nu72vocnofKcpXLEQKppkalshZWNgdXA
"""

n = int(input('How many numbers do you want to input : '))
number = []

for a in range (0, n):
  a = int(input('Please input number : '))
  if a > 0 :
    number.append(a)
    #print(a)
    #print(number)
  while a < 0 :
    print("Cannot put minus interger. please input positive integer.")
    a = int(input('Please input number : '))
    if a > 0 :
      number.append(a)
print('The numbers that you want to form the largest number are', number)

for i in range(len(number)):
  number[i] = str(number[i])

for i in range(len(number)):
  for j in range(1+i,len(number)):
    if number[j] + number[i] > number[i] + number[j]:
      number[i],number[j]=number[j],number[i]

result = ''.join(number)
print('The largest formed number is', result)